Script started on Fri 29 May 2015 01:38:07 PM PDT
~
jpatu001@hammer $ cd C[KDocuments/CS100/rshell/
~/Documents/CS100/rshell
jpatu001@hammer $ make
if [ ! -d bin ]; then mkdir bin; fi
g++ -ansi -pedantic -Wall -Werror  src/main.cpp -o bin/rshell
g++ -ansi -pedantic -Wall -Werror  src/cp.cpp -o bin/cp
g++ -ansi -pedantic -Wall -Werror  src/ls.cpp -o bin/ls
g++ -ansi -pedantic -Wall -Werror  src/mv.cpp -o bin/mv
g++ -ansi -pedantic -Wall -Werror  src/rm.cpp -o bin/rm
~/Documents/CS100/rshell
jpatu001@hammer $ bin/rshell
jpatu001@hammer:~/Documents/CS100/rshell $ # ~ is for home, (extra x credit part)
jpatu001@hammer:~/Documents/CS100/rshell $ # ~ is followed by current working directory(Q #2)
jpatu001@hammer:~/Documents/CS100/rshell $ # now cd has to take me to c home
jpatu001@hammer:~/Documents/CS100/rshell $ cd
jpatu001@hammer:~ $ ps
  PID TTY          TIME CMD
40459 pts/17   00:00:00 bash
40553 pts/17   00:00:00 rshell
40704 pts/17   00:00:00 ps
jpatu001@hammer:~ $ pwd
/home/csmajs/jpatu001
jpatu001@hammer:~ $ #here you see I'm at home directory
jpatu001@hammer:~ $ # cd - should bring me back to my previous directory 
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Documents/CS100/rshell $ #now I'm back to rpev   p  prevsious directory
jpatu001@hammer:~/Documents/CS100/rshell $ cd -
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Documents/CS100/rshell $ c cd
jpatu001@hammer:~ $ cd ..
jpatu001@hammer:/home/csmajs $ cd ..
jpatu001@hammer:/home $ cd ..
jpatu001@hammer:/ $ pwd
/
jpatu001@hammer:/ $ #here I'm way below the home directory, now using cd i'll be back at home
jpatu001@hammer:/ $ cd
jpatu001@hammer:~ $ ps
  PID TTY          TIME CMD
40459 pts/17   00:00:00 bash
40553 pts/17   00:00:00 rshell
40830 pts/17   00:00:00 ps
jpatu001@hammer:~ $ pwd
/home/csmajs/jpatu001
jpatu001@hammer:~ $ # back at home again. So it works anywhere I am
jpatu001@hammer:~ $ # cd <path>
jpatu001@hammer:~ $ cd Doc	ue ments
jpatu001@hammer:~/Documents $ cd ..
jpatu001@hammer:~ $ cd Desktop
jpatu001@hammer:~/Desktop $ cd ..
jpatu001@hammer:~ $ cd Documents/CS100/rshell/src
jpatu001@hammer:~/Documents/CS100/rshell/src $ cd -
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Documents/CS100/rshell/src $ cd -
jpatu001@hammer:~ $ # cd <non-exisin t  ting path>
jpatu001@hammer:~ $ cd nonexistingpath
chdir(): No such file or directory
jpatu001@hammer:~ $ cd nonexisting  path 2  2
chdir(): No such file or directory
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~ $ cd Documents        esktop
jpatu001@hammer:~/Desktop $ # cd absolute path
jpatu001@hammer:~/Desktop $ cd /home/csmajs/jpatu001/Documents/rsh   CS100/rshell
jpatu001@hammer:~/Documents/CS100/rshell $ cd -
jpatu001@hammer:~/Desktop $ cd -
jpatu001@hammer:~/Documents/CS100/rshell $ cd -
jpatu001@hammer:~/Desktop $ # cd, cd - , cd <path  > all working. one more run over all of them
jpatu001@hammer:~/Desktop $ cd 
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Desktop $ cd -
jpatu001@hammer:~ $ cd Documents/CS100/rshell/bon  in
jpatu001@hammer:~/Documents/CS100/rshell/bin $ cd -
jpatu001@hammer:~ $ cd Documents/nonexisting
chdir(): No such file or directory
jpatu001@hammer:~ $ cd Documents/CS100/rsehl   hell/src
jpatu001@hammer:~/Documents/CS100/rshell/src $ cd /home/csmajs/jpatu001/Desktop
jpatu001@hammer:~/Desktop $ cd
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Desktop $ cd -
jpatu001@hammer:~ $ cd -
jpatu001@hammer:~/Desktop $ cd -
jpatu001@hammer:~ $ 
jpatu001@hammer:~ $ 
jpatu001@hammer:~ $ 
jpatu001@hammer:~ $ ### TESTING CTRL C ###
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ #didnt quit as it shoud ld
jpatu001@hammer:~ $ cat
now waiting for inputs
now waiting for inputs
should quit this when i do ctrl c
should quit this when i do ctrl c
^C
jpatu001@hammer:~ $ #quit as it should
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ #didnt quit as it d should
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ ^C
jpatu001@hammer:~ $ Done    ### DONE ###
jpatu001@hammer:~ $ exit
~/Documents/CS100/rshell
jpatu001@hammer $ exit
exit

Script done on Fri 29 May 2015 01:44:09 PM PDT
